version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./app
    ports:
      - "5000:5000"
    command: gunicorn -w 1 -b 0.0.0.0:5000 app:app
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "8001:80"
    depends_on:
      - flask_app